# Generated by Django 2.0.3 on 2018-03-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='projects/')),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
