# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models

def set_show_article_section(apps, schema_editor):
    "hide the series articles on this migration"
    Article = apps.get_model("blog", "Article")
    for series_article in Article.objects.filter(series__isnull=False):
        series_article.show_article_section = False
        series_article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_article_section',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_show_article_section)
    ]
