# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_show_article_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_card_title',
            field=models.BooleanField(default=True),
        ),
    ]
